### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by the-sageman** [FChannel0/FChannel-Server#26] opened 2021-07-02 11:39 UTC
Currently, fchannel's release scheme is a mess. Why does the minor version have its own variations like the `c` in `v0.0.5c` as it is today? Git hashes might look like a mess, but I believe this project should follow the industry, or, well, open source standard of using git hashes if it is cloned straight off the repository and a normal version number if it is downloaded from an official release.

**Comment by knotteye** [comment] 2021-07-02 11:58
It is kind of a mess. Contributing as a bit of a headache as well since everything happens on master. My recommendation would be to use master as the 'stable' branch that can always be cloned and built, and have a `develop` branch for unstable or still in testing features. Then master pulls from develop every time a new release is cut.

Depending on how in-depth the dev wants to get we could also do `feature/X` branches but that might be getting off topic.

**Comment by FChannel0** [comment] 2021-07-02 15:29
I added the current versioning just to be able to see check other instances versions to see which they are on to track bugs. There was a bug before v0.0.5 that broke federation by not populating the `to` field correctly. The alpha characters at the end are minor changes to that minor version which didnt add anything substantial. Sure, following some industry standard would be better. Could just add v0.0.5.1 or something. Mostly it was just so I can check what version of the code a instance is running if they have issues. 

> My recommendation would be to use master as the 'stable' branch that can always be cloned and built, and have a develop branch for unstable or still in testing features.

This is a good suggestions and I will start implementing it. The project is getting more attention than just me working on it, so there should be better management.

**Comment by the-sageman** [comment] 2021-07-02 16:12
> 
> 
> I added the current versioning just to be able to see check other instances versions to see which they are on to track bugs. There was a bug before v0.0.5 that broke federation by not populating the `to` field correctly. The alpha characters at the end are minor changes to that minor version which didnt add anything substantial. Sure, following some industry standard would be better. Could just add v0.0.5.1 or something. Mostly it was just so I can check what version of the code a instance is running if they have issues.
> 
> > My recommendation would be to use master as the 'stable' branch that can always be cloned and built, and have a develop branch for unstable or still in testing features.
> 
> This is a good suggestions and I will start implementing it. The project is getting more attention than just me working on it, so there should be better management.

How about then `v0.0.5-release` for official releases in `master` and in the GitHub Releases tab and `v0.0.5-development` which will link to the last commit that the site is running on?

**Comment by FChannel0** [comment] 2021-07-02 17:06
> How about then `v0.0.5-release` for official releases in `master` and in the GitHub Releases tab and `v0.0.5-development` which will link to the last commit that the site is running on?

That is a good approach. Ill implement it sometime today.

**Comment by FChannel0** [comment] 2021-07-03 18:00
@knotteye @the-sageman 
OK, I am going to split up some branches right now, since you two are the ones working with the codebase the mode I will consult you. 

`v0.0.5-release` is same as master
`v0.0.6-development` is current 'nightly' builds that fchan.xyz will be running
`v0.0.6-testing` is same as development except this is where Pull Requests should be merged with and then if everything tests ok, it gets merged with development, then if things are stable it gets merged with release.

let me know which workflow works for you two. I am waiting to merge the current PR until a testing branch gets implemented, don't want to have other instances pull a commit that needs further testing.

**Comment by knotteye** [comment] 2021-07-03 18:56
So 3 branches, PRs go to `testing` and get merged with `development` once they're confirmed working, and `master` is the release branch that merges from `development`?

That sounds good to me. I'll change my PR to merge with `testing` once it's created.

**Comment by the-sageman** [comment] 2021-07-03 19:33
> 
> 
> @knotteye @the-sageman
> OK, I am going to split up some branches right now, since you two are the ones working with the codebase the most I will consult you.
> 
> `v0.0.5-release` is same as master
> `v0.0.6-development` is current 'nightly' builds that fchan.xyz will be running
> `v0.0.6-testing` is same as development except this is where Pull Requests should be merged with and then if everything tests ok, it gets merged with development, then if things are stable it gets merged with release.
> 
> let me know which workflow works for you two. I am waiting to merge the current PR until a testing branch gets implemented, don't want to have other instances pull a commit that needs further testing.

I find  `v0.0.6-testing` a bit odd. Shouldn't pull requests have some basic testing performed on them before they are merged or is there a test suite planned?

**Comment by FChannel0** [comment] 2021-07-03 19:55
> > @knotteye @the-sageman
> > OK, I am going to split up some branches right now, since you two are the ones working with the codebase the most I will consult you.
> > `v0.0.5-release` is same as master
> > `v0.0.6-development` is current 'nightly' builds that fchan.xyz will be running
> > `v0.0.6-testing` is same as development except this is where Pull Requests should be merged with and then if everything tests ok, it gets merged with development, then if things are stable it gets merged with release.
> > let me know which workflow works for you two. I am waiting to merge the current PR until a testing branch gets implemented, don't want to have other instances pull a commit that needs further testing.
> 
> I find `v0.0.6-testing` a bit odd. Shouldn't pull requests have some basic testing performed on them before they are merged or is there a test suite planned?

Test cases will be planned, but for now I was thinking that the test branch being where PR are merged so I can test before going to development. It might seem redundent but if development is what fchan is running I want to be able to test the PR before adding it to development, just in case something gets missed with the PR. So if something goes wrong I don't have the reset the development branch to go back to a working state.

**Comment by knotteye** [comment] 2021-07-03 19:57
I think it's useful to have a place to leave known non-working code. Like in #30 the javascript form validation broke board creation. With only stable and stable-ish you need to revert the commit so it's in a usable state but you can leave it if you have a "might be totally broken" branch you can leave it in so that another PR can fix it.

Then you merge 'no known bugs' code to development and more adventurous admins can test your code for you without having to stay on a branch that might be fucked sometimes.

**Comment by the-sageman** [comment] 2021-07-03 20:13
Another thing I have in mind, versions should not be in the branch names, it is better if you tag those instead @FChannel0, `master` is going to stay, and that's where releases are going to be staged from, `develop` is where unstable but somewhat stable changes are going to be on, and `testing` is where totally unstable changes are. So if admins follow `testing`, then they are  totally reckless or testers, but `develop` is where experimental changes are tested which are known to not break in most cases and it can be (a still bit recklessly but) safely followed.

How about hotfixes which fix critical bugs? Are they going to be merged straight into `master`? How about reverting a certain commit whose final file(s) have been committed to several times? Who's going to do the reverting?

**Comment by knotteye** [comment] 2021-07-03 20:22
@FChannel0 is the only person with write access so not much choice about who is doing the reverting. I do have the same question about hotfixes though, they would either need to be cherry-picked (can github do cherry picking easily?) or need a PR to all 3 branches I guess.

**Comment by FChannel0** [comment] 2021-07-03 20:58
After thinking about, could just use two branches. 

Master will be current stable(?)
Development nightly testing use if you want to help find bugs

Everyone works off development, if something breaks with the PR while testing reset branch to state before PR, person that made a PR would have to revise and recommit if not a simple fix.

If there is a critical bug fix it goes to development and then merged with master with all previous development changes to that point, this could be a new version or if it was a hotfix right after a new version a new minor of current version if needed to be noted.

**Comment by the-sageman** [comment] 2021-07-03 21:05
> If there is a critical bug fix it goes to development and then merged with master with all previous development changes to that point
sounds like a recipe for disaster to me, how about a occasional separate branch based on `master` for hotfixes?

**Comment by FChannel0** [comment] 2021-07-03 21:18
> > If there is a critical bug fix it goes to development and then merged with master with all previous development changes to that point
> 
> sounds like a recipe for disaster to me, how about a occasional separate branch based on `master` for hotfixes?

This is under the assumption that development do not break all the time and can be easily moved up to master. If it is believed there needs to be another barrier I am fine with that. 

For now there will be master and development. If a hotfix needs to be contained there can be one based on master.

**Comment by knotteye** [comment] 2021-07-03 21:54
> > If there is a critical bug fix it goes to development and then merged with master with all previous development changes to that point
> 
> sounds like a recipe for disaster to me, how about a occasional separate branch based on `master` for hotfixes?

Yeah I'm not a fan of that either, I think it's better to just backport fixes straight to master (or a temporary branch that gets merged with master) when absolutely necessary. Better to spend an hour backporting a fix than discovering a bunch of new bugs in development when they go live with no warning.

**Closed** 2021-07-04 03:43 UTC
